sfdx-source/OrgTreeCmp/main/default/objects/OrgTreeConfig__c/OrgTreeConfig__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>組織情報DX設定</label>
</CustomObject>

sfdx-source/OrgTreeCmp/main/default/objects/OrgTreeConfig__c/fields/AccountOrgField__c.field-meta.xml
<CustomField>
    <fullName>AccountOrgField__c</fullName>
    <defaultValue>&apos;Name&apos;</defaultValue>
    <label>取引先: 組織名の項目</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/OrgTreeCmp/main/default/objects/OrgTreeConfig__c/fields/AccountTreeGridColumns__c.field-meta.xml
<CustomField>
    <fullName>AccountTreeGridColumns__c</fullName>
    <defaultValue>&apos;SmartViscaf__NameCard__c, OwnerId&apos;</defaultValue>
    <label>取引先: グリッドに表示する項目</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/OrgTreeCmp/main/default/objects/OrgTreeConfig__c/fields/ContactTreeGridColumns__c.field-meta.xml
<CustomField>
    <fullName>ContactTreeGridColumns__c</fullName>
    <defaultValue>&apos;Title, Phone, MobilePhone, EMail, SmartViscaf__NameCard__c, ContactRole, OwnerId&apos;</defaultValue>
    <label>取引先責任者: グリッドに表示する項目</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/OrgTreeCmp/main/default/objects/OrgTreeConfig__c/fields/LeadOrgField__c.field-meta.xml
<CustomField>
    <fullName>LeadOrgField__c</fullName>
    <defaultValue>&apos;Company&apos;</defaultValue>
    <label>[不使用] リード: 組織名の項目</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/OrgTreeCmp/main/default/objects/OrgTreeConfig__c/fields/LeadTreeGridColumns__c.field-meta.xml
<CustomField>
    <fullName>LeadTreeGridColumns__c</fullName>
    <defaultValue>&apos;Title, Phone, MobilePhone, EMail, SmartViscaf__NameCard__c, OwnerId&apos;</defaultValue>
    <label>[不使用] リード: グリッドに表示する項目</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/OrgTreeCmp/main/default/objects/OrgTreeConfig__c/fields/NameCardOrgField__c.field-meta.xml
<CustomField>
    <fullName>NameCardOrgField__c</fullName>
    <defaultValue>&apos;SmartViscaf__company_name__c&apos;</defaultValue>
    <label>名刺: 組織名の項目</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/OrgTreeCmp/main/default/objects/OrgTreeConfig__c/fields/NameCardTreeGridColumns__c.field-meta.xml
<CustomField>
    <fullName>NameCardTreeGridColumns__c</fullName>
    <defaultValue>&apos;SmartViscaf__title_name__c, SmartViscaf__email__c, SmartViscaf__card_exchange_date__c, SmartViscaf__account__c, SmartViscaf__contact__c, OwnerId&apos;</defaultValue>
    <label>名刺: グリッドに表示する項目</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/OrgTreeCmp/main/default/classes/SB_Ot_GlobalTest.cls
@isTest
private class SB_Ot_GlobalTest {

  @isTest
  static void test_getNamespacePrefix_x() {
    String ns = SB_Ot_Global.getNamespacePrefix();
    String nsx = SB_Ot_Global.getNamespacePrefix_x();
    List<ApexClass> classes = [SELECT Name, NamespacePrefix FROM ApexClass WHERE Name='SB_Ot_Global'];
    if (classes.isEmpty()) {
      System.assert(String.isBlank(ns));
      System.assert(String.isBlank(nsx));
    }
    else {
      System.assert(String.isNotBlank(ns));
      System.assert((nsx.endsWith('__')));
    }
  }

  @isTest
  static void test_isEnableSmartVisca() {
    System.assertEquals(SB_Ot_Global.getNameCardSObjectType() != null, SB_Ot_Global.isEnableSmartVisca());
  }

  @isTest
  static void test_isEnableLeadExtension() {
    Map<string, Schema.SObjectField> leadFieldMap = Lead.getSObjectType().getDescribe().fields.getMap();
    System.assertEquals(leadFieldMap.containsKey('smartviscal__namecard__c'), SB_Ot_Global.isEnableLeadExtension());
  }

  @isTest
  static void test_SmartVisca() {
    System.assertEquals(SB_Ot_Global.isEnableSmartVisca(), SB_Ot_Global.getNameCardSObjectType() != null);
  }

  @isTest
  static void test_isEnablePersonAccount() {
    Boolean enabelPerson = Account.getSObjectType().getDescribe().fields.getMap().containsKey('IsPersonAccount');
    System.assertEquals(enabelPerson, SB_Ot_Global.isEnablePersonAccount());
  }

  @isTest
  static void test_TreeGridColumns_null() {
    // カスタム設定のデフォルト値をクリア
    OrgTreeConfig__c config = new OrgTreeConfig__c();
    config.AccountOrgField__c = null;
    config.LeadOrgField__c = null;
    config.NameCardOrgField__c = null;
    config.AccountTreeGridColumns__c = null;
    config.ContactTreeGridColumns__c = null;
    config.LeadTreeGridColumns__c = null;
    config.NameCardTreeGridColumns__c = null;
    insert config;

    // Id だけは必須で入る。
    System.assertEquals('Name', SB_Ot_Global.otConfig.AccountOrgField__c);
    System.assertEquals('Company', SB_Ot_Global.otConfig.LeadOrgField__c);
    System.assertEquals('SmartViscaf__company_name__c', SB_Ot_Global.otConfig.NameCardOrgField__c);
    System.assertEquals('Id', SB_Ot_Global.otConfig.AccountTreeGridColumns__c);
    System.assertEquals('Id', SB_Ot_Global.otConfig.ContactTreeGridColumns__c);
    System.assertEquals('Id', SB_Ot_Global.otConfig.LeadTreeGridColumns__c);
    System.assertEquals('Id', SB_Ot_Global.otConfig.NameCardTreeGridColumns__c);
  }
}