sfdx-source/OrgTreeCmp/main/default/objects/OrgTreeConfig__c/OrgTreeConfig__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>組織情報DX設定</label>
</CustomObject>

sfdx-source/OrgTreeCmp/main/default/objects/OrgTreeConfig__c/fields/AccountOtherCondition__c.field-meta.xml
<CustomField>
    <fullName>AccountOtherCondition__c</fullName>
    <defaultValue>0</defaultValue>
    <description>0: なし
1: 名刺への参照があるレコードのみ (省略値)
2: 最新の名刺への参照があるレコードのみ
3: 転職していない最新の名刺への参照があるレコードのみ
親子関係の取引先レコードに関して有効</description>
    <label>取引先: 対象レコードの条件</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/OrgTreeCmp/main/default/objects/OrgTreeConfig__c/fields/ContactOtherCondition__c.field-meta.xml
<CustomField>
    <fullName>ContactOtherCondition__c</fullName>
    <defaultValue>0</defaultValue>
    <description>0: なし
1: 名刺への参照があるレコードのみ (省略値)
2: 最新の名刺への参照があるレコードのみ
3: 転職していない最新の名刺への参照があるレコードのみ</description>
    <label>取引先責任者: 対象レコードの条件</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/OrgTreeCmp/main/default/objects/OrgTreeConfig__c/fields/LeadOtherCondition__c.field-meta.xml
<CustomField>
    <fullName>LeadOtherCondition__c</fullName>
    <defaultValue>0</defaultValue>
    <description>0: なし
1: 名刺への参照があるレコードのみ (省略値)
2: 最新の名刺への参照があるレコードのみ
3: 転職していない最新の名刺への参照があるレコードのみ</description>
    <label>[不使用] リード: 対象レコードの条件</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/OrgTreeCmp/main/default/objects/OrgTreeConfig__c/fields/LeadTreeGridColumns__c.field-meta.xml
<CustomField>
    <fullName>LeadTreeGridColumns__c</fullName>
    <defaultValue>&apos;Title, Phone, MobilePhone, EMail, SmartViscaf__NameCard__c, OwnerId&apos;</defaultValue>
    <label>[不使用] リード: グリッドに表示する項目</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/OrgTreeCmp/main/default/objects/OrgTreeConfig__c/fields/UserOtherCondition__c.field-meta.xml
<CustomField>
    <fullName>UserOtherCondition__c</fullName>
    <defaultValue>1</defaultValue>
    <description>0: なし
1: 有効なユーザのみ
2: 同じ組織のユーザのみ
3: 同じ組織の有効なユーザのみ</description>
    <label>[不使用] ユーザ: 対象レコードの条件</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/OrgTreeCmp/main/default/classes/SB_Ot_OrgTreeFactoryTest3.cls
/**
 *
 *  SB_Ot_OrgTreeFactoryTest3
 *    SB_Ot_OrgTreeFactory のテストクラス  他オブジェクト の階層ノード作成 のテスト
 *
 * Copyright (C) 2019 SunBridge Inc. All Rights Reserved.
 *
 *  @author sawano
 *  @Version 1.1      2019.05.xx
 *
 */
@isTest
private class SB_Ot_OrgTreeFactoryTest3 {

  private static List<Account> createChildAccount(List<Account> parents) {
    List<Account> result = new List<Account>();
    for (Account parent : parents) {
      result.add(new Account(Name=parent.Name+'01', ParentId=parent.Id));
      result.add(new Account(Name=parent.Name+'02', ParentId=parent.Id));
    }
    insert result;
    return result;
  }

  private static List<Contact> createContacts(List<Account> acnts) {
    List<Contact> result = new List<Contact>();
    for (Account acnt : acnts) {
      result.add(new Contact(LastName=acnt.Name+'社員01', FirstName='太郎', Department='開発部 開発課', Title='課長', Email='taro@' + acnt.Id + '.com', AccountId=acnt.Id));
      result.add(new Contact(LastName=acnt.Name+'社員02', FirstName='次郎', Department='営業部 営業課', Title='課長', Email='jiro@' + acnt.Id + '.com', AccountId=acnt.Id));
    }
    insert result;
    return result;
  }

  @TestSetup
  static void setupAccountsContacsLeads() {
    List<Account> acnts = new List<Account>();
    List<Contact> conts;
    acnts.add(new Account(Name='エンタ株式会社'));  // 1
    insert acnts;
    conts = createContacts(acnts);      // 2
    acnts = createChildAccount(acnts);      // 1+2
    conts = createContacts(acnts);      // 2+4
    acnts = createChildAccount(acnts);      // 3+4
    conts = createContacts(acnts);      // 6+8

    // Lead に Account, Contact に対応するのを作っておく
    conts = [SELECT Id, Name, FirstName, LastName, Email, Title, Department, Account.Name FROM Contact];
    List<Lead> leads = new List<Lead>();
    for (Contact c : conts) {
      leads.add(new Lead(Company=c.Account.Name, Title = c.Title, FirstName=c.FirstName, LastName=c.LastName, Email=c.Email));
    }
    insert leads;
    // カスタム設定を初期化
    OrgTreeConfig__c config = new OrgTreeConfig__c();
    config.LeadTreeGridColumns__c = 'Title, Phone, MobilePhone, Email';
    config.AccountOtherCondition__c = 0;
    config.ContactOtherCondition__c = 0;
    config.LeadOtherCondition__c = 0;
    config.UserOtherCondition__c = 0;
    insert config;
  }

  @isTest
  static void test_createOrgTreeItems_by_Lead_from_Account() {
    Account rootAcnt = [SELECT Id, Name FROM Account WHERE ParentId = null LIMIT 1];
    List<Account> acnts = [SELECT Id, Name FROM Account WHERE ParentId != null];

    List<SB_Ot_OrgTreeItem.Item> items = SB_Ot_OrgTreeFactory.createOrgTreeItems(acnts[0].Id, Lead.getSObjectType());
    SB_Ot_OrgTreeItem.TreeItem root = (SB_Ot_OrgTreeItem.TreeItem)items[0];
    root.print();
    System.assert(root.label.startsWith(rootAcnt.Name));
  }

  @isTest
  static void test_createOrgGridItems_by_Lead_from_Account() {
    // カスタム設定をデフォルトからOwenrIdを外して初期化 LeadのOwnerは特別？
    // OrgTreeConfig__c config = new OrgTreeConfig__c();
    // config.LeadTreeGridColumns__c = 'Title, Phone, MobilePhone, Email';
    // insert config;
    Account rootAcnt = [SELECT Id, Name FROM Account WHERE ParentId = null LIMIT 1];
    List<Account> acnts = [SELECT Id, Name FROM Account WHERE ParentId != null];

    List<SB_Ot_OrgTreeItem.Item> items = SB_Ot_OrgTreeFactory.createOrgGridItems(acnts[0].Id, Lead.getSObjectType());
    SB_Ot_OrgTreeItem.GridItem root = (SB_Ot_OrgTreeItem.GridItem)items[0];
    root.print();
    System.assert(root.label.startsWith(rootAcnt.Name));
  }

  @isTest
  static void test_createOrgTreeItems_by_Lead_from_Contact() {
    Account rootAcnt = [SELECT Id, Name FROM Account WHERE ParentId = null LIMIT 1];
    List<Contact>  conts = [SELECT Id, Name FROM Contact];

    List<SB_Ot_OrgTreeItem.Item> items = SB_Ot_OrgTreeFactory.createOrgTreeItems(conts[0].Id, Lead.getSObjectType());
    SB_Ot_OrgTreeItem.TreeItem root = (SB_Ot_OrgTreeItem.TreeItem)items[0];
    root.print();
    System.assert(root.label.startsWith(rootAcnt.Name));
  }

  @isTest
  static void test_createOrgGridItems_by_Lead_from_Contact() {
    // カスタム設定をデフォルトからOwenrIdを外して初期化 LeadのOwnerは特別？
    // OrgTreeConfig__c config = new OrgTreeConfig__c();
    // config.LeadTreeGridColumns__c = 'Title, Phone, MobilePhone, Email';
    // insert config;
    Account rootAcnt = [SELECT Id, Name FROM Account WHERE ParentId = null LIMIT 1];
    List<Contact>  conts = [SELECT Id, Name FROM Contact];

    List<SB_Ot_OrgTreeItem.Item> items = SB_Ot_OrgTreeFactory.createOrgGridItems(conts[0].Id, Lead.getSObjectType());
    SB_Ot_OrgTreeItem.GridItem root = (SB_Ot_OrgTreeItem.GridItem)items[0];
    root.print();
    System.assert(root.label.startsWith(rootAcnt.Name));
  }

  @isTest
  static void test_createOrgTreeItems_by_Account_from_Lead() {
    List<Lead> leads = [SELECT Id, Name, Company FROM Lead];

    List<SB_Ot_OrgTreeItem.Item> items = SB_Ot_OrgTreeFactory.createOrgTreeItems(leads[0].Id, Account.getSObjectType());
    SB_Ot_OrgTreeItem.TreeItem root = (SB_Ot_OrgTreeItem.TreeItem)items[0];
    root.print();
    System.assert(root.label.startsWith(leads[0].Company));
  }

  @isTest
  static void test_createOrgGridItems_by_Account_from_Lead() {
    List<Lead> leads = [SELECT Id, Name, Company FROM Lead];

    List<SB_Ot_OrgTreeItem.Item> items = SB_Ot_OrgTreeFactory.createOrgGridItems(leads[0].Id, Account.getSObjectType());
    SB_Ot_OrgTreeItem.GridItem root = (SB_Ot_OrgTreeItem.GridItem)items[0];
    root.print();
    System.assert(root.label.startsWith(leads[0].Company));
  }

}