sfdx-source/OrgTreeCmp/main/default/objects/OrgTreeConfig__c/OrgTreeConfig__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>組織情報DX設定</label>
</CustomObject>

sfdx-source/OrgTreeCmp/main/default/objects/OrgTreeConfig__c/fields/MultiObject__c.field-meta.xml
<CustomField>
    <fullName>MultiObject__c</fullName>
    <defaultValue>&quot;Lead,Account,Contact,SmartViscaf__NameCard__c&quot;</defaultValue>
    <label>[不使用] MultiObject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/OrgTreeCmp/main/default/objects/OrgTreeConfig__c/fields/MultiObjectActive__c.field-meta.xml
<CustomField>
    <fullName>MultiObjectActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>[不使用] MultiObjectActive</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/OrgTreeCmp/main/default/objects/OrgTreeConfig__c/fields/MultiObjectTreeGridColumns1__c.field-meta.xml
<CustomField>
    <fullName>MultiObjectTreeGridColumns1__c</fullName>
    <defaultValue>&apos;Title, Phone, MobilePhone, EMail, SmartViscaf__NameCard__c, OwnerId, sobject&apos;</defaultValue>
    <label>[不使用] MultiObjectTreeGridColumns1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/OrgTreeCmp/main/default/classes/SB_Ot_LcRequestObjectPickListTest.cls
/**
 *  SB_Ot_LcRequestObjectPickListTest
 *
 *  SB_Ot_LcRequestObjectPickList のテストクラス
 *
 * Copyright (C) 2019 SunBridge Inc. All Rights Reserved.
 *
 *  @author sawano
 *  @Version 1    2019.05.xx
 *
 **/
@isTest
private class SB_Ot_LcRequestObjectPickListTest {

  @isTest
  static void test_SB_Ot_LcRequestObjectPickList_Account() {
    // カスタム設定の複数オブエジェクト対応の設定
    OrgTreeConfig__c config = new OrgTreeConfig__c();
    config.MultiObjectActive__c = true;
    config.MultiObject__c = 'Lead,Account,Contact,SmartViscaf__NameCard__c';
    config.MultiObjectTreeGridColumns1__c = 'Title, Phone, MobilePhone, EMail, SmartViscaf__NameCard__c, OwnerId, sobject';
    insert config;

    VisualEditor.DesignTimePageContext context = new VisualEditor.DesignTimePageContext();
    context.entityName = 'Account';
    SB_Ot_LcRequestObjectPickList pickList = new SB_Ot_LcRequestObjectPickList(context);
    System.assertEquals('account', pickList.getDefaultValue().getValue());
    VisualEditor.DynamicPickListRows opts = pickList.getValues();
    System.assert(opts.size() > 0);
  }

  @isTest
  static void test_SB_Ot_LcRequestObjectPickList_Contact() {
    // カスタム設定の複数オブエジェクト対応の設定
    OrgTreeConfig__c config = new OrgTreeConfig__c();
    config.MultiObjectActive__c = true;
    config.MultiObject__c = 'Lead,Account,Contact,SmartViscaf__NameCard__c';
    config.MultiObjectTreeGridColumns1__c = 'Title, Phone, MobilePhone, EMail, SmartViscaf__NameCard__c, OwnerId, sobject';
    insert config;

    VisualEditor.DesignTimePageContext context = new VisualEditor.DesignTimePageContext();
    context.entityName = 'Contact';
    SB_Ot_LcRequestObjectPickList pickList = new SB_Ot_LcRequestObjectPickList(context);
    System.assertEquals('account', pickList.getDefaultValue().getValue());
    VisualEditor.DynamicPickListRows opts = pickList.getValues();
    System.assert(opts.size() > 0);
  }


}