sfdx-source/OrgTreeCmp/main/default/objects/OrgTreeConfig__c/OrgTreeConfig__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>組織情報DX設定</label>
</CustomObject>

sfdx-source/OrgTreeCmp/main/default/objects/OrgTreeConfig__c/fields/AccountAssociation__c.field-meta.xml
<CustomField>
    <fullName>AccountAssociation__c</fullName>
    <defaultValue>true</defaultValue>
    <label>取引先: 親・子の取引先を階層に含める</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/OrgTreeCmp/main/default/objects/OrgTreeConfig__c/fields/AccountOtherCondition__c.field-meta.xml
<CustomField>
    <fullName>AccountOtherCondition__c</fullName>
    <defaultValue>0</defaultValue>
    <description>0: なし
1: 名刺への参照があるレコードのみ (省略値)
2: 最新の名刺への参照があるレコードのみ
3: 転職していない最新の名刺への参照があるレコードのみ
親子関係の取引先レコードに関して有効</description>
    <label>取引先: 対象レコードの条件</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/OrgTreeCmp/main/default/objects/OrgTreeConfig__c/fields/ContactOtherCondition__c.field-meta.xml
<CustomField>
    <fullName>ContactOtherCondition__c</fullName>
    <defaultValue>0</defaultValue>
    <description>0: なし
1: 名刺への参照があるレコードのみ (省略値)
2: 最新の名刺への参照があるレコードのみ
3: 転職していない最新の名刺への参照があるレコードのみ</description>
    <label>取引先責任者: 対象レコードの条件</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/OrgTreeCmp/main/default/objects/OrgTreeConfig__c/fields/ContactTreeGridColumns__c.field-meta.xml
<CustomField>
    <fullName>ContactTreeGridColumns__c</fullName>
    <defaultValue>&apos;Title, Phone, MobilePhone, EMail, SmartViscaf__NameCard__c, ContactRole, OwnerId&apos;</defaultValue>
    <label>取引先責任者: グリッドに表示する項目</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/OrgTreeCmp/main/default/objects/OrgTreeConfig__c/fields/LeadOtherCondition__c.field-meta.xml
<CustomField>
    <fullName>LeadOtherCondition__c</fullName>
    <defaultValue>0</defaultValue>
    <description>0: なし
1: 名刺への参照があるレコードのみ (省略値)
2: 最新の名刺への参照があるレコードのみ
3: 転職していない最新の名刺への参照があるレコードのみ</description>
    <label>[不使用] リード: 対象レコードの条件</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/OrgTreeCmp/main/default/objects/OrgTreeConfig__c/fields/PrioritizeCustomSetting__c.field-meta.xml
<CustomField>
    <fullName>PrioritizeCustomSetting__c</fullName>
    <defaultValue>false</defaultValue>
    <label>カスタム設定を優先する</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/OrgTreeCmp/main/default/objects/OrgTreeConfig__c/fields/UserOtherCondition__c.field-meta.xml
<CustomField>
    <fullName>UserOtherCondition__c</fullName>
    <defaultValue>1</defaultValue>
    <description>0: なし
1: 有効なユーザのみ
2: 同じ組織のユーザのみ
3: 同じ組織の有効なユーザのみ</description>
    <label>[不使用] ユーザ: 対象レコードの条件</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/OrgTreeCmp/main/default/classes/SB_Ot_OrgTreeFactoryTest2.cls
/**
 *
 *  SB_Ot_OrgTreeFactoryTest2
 *    SB_Ot_OrgTreeFactory のテストクラス  アカウント、コンタクト の階層ノード作成 のテスト
 *
 * Copyright (C) 2019 SunBridge Inc. All Rights Reserved.
 *
 *  @author sawano
 *  @Version 1.0      2019.03.xx
 *
 */
@isTest
private class SB_Ot_OrgTreeFactoryTest2 {

  private static List<Account> createChildAccount(List<Account> parents) {
    List<Account> result = new List<Account>();
    for (Account parent : parents) {
      result.add(new Account(Name=parent.Name+'01', ParentId=parent.Id));
      result.add(new Account(Name=parent.Name+'02', ParentId=parent.Id));
    }
    insert result;
    return result;
  }

  private static List<Contact> createContacts(List<Account> acnts) {
    List<Contact> result = new List<Contact>();
    for (Account acnt : acnts) {
      result.add(new Contact(LastName=acnt.Name+'社員01', FirstName='太郎', Department='開発部 開発課', Title='課長', Email='taro@' + acnt.Id + '.com',
            AccountId=acnt.Id, MailingPostalCode='150-0022', MailingState='東京都', MailingCity='渋谷区', MailingStreet='恵比寿南1-5-5'));
      result.add(new Contact(LastName=acnt.Name+'社員02', FirstName='次郎', Department='営業部 営業課', Title='課長', Email='jiro@' + acnt.Id + '.com',
            AccountId=acnt.Id, MailingPostalCode='150-0022', MailingState='東京都', MailingCity='渋谷区', MailingStreet='恵比寿南1-5-5'));
    }
    insert result;
    return result;
  }

  @TestSetup
  static void setupAccountsContacs() {
    List<Account> acnts = new List<Account>();
    List<Contact> conts;
    acnts.add(new Account(Name='エンタ株式会社'));  // 1
    insert acnts;
    conts = createContacts(acnts);      // 2
    acnts = createChildAccount(acnts);      // 1+2
    conts = createContacts(acnts);      // 2+4
    acnts = createChildAccount(acnts);      // 3+4
    conts = createContacts(acnts);      // 6+8

    // カスタム設定を初期化
    OrgTreeConfig__c config = new OrgTreeConfig__c();
    config.PrioritizeCustomSetting__c = true;  // カスタム設定を優先する
    config.AccountAssociation__c = true;      // 取引先 親・子の取引先を階層に含める#
    config.ContactTreeGridColumns__c = 'Title, Phone, MobilePhone, EMail, MailingAddress, OwnerId';
    config.AccountOtherCondition__c = 0;
    config.ContactOtherCondition__c = 0;
    config.LeadOtherCondition__c = 0;
    config.UserOtherCondition__c = 0;
    insert config;
  }

  @isTest
  static void test_createOrgTreeItems_by_Account() {
    Account rootAcnt = [SELECT Id, Name FROM Account WHERE ParentId = null LIMIT 1];
    List<Account> acnts = [SELECT Id, Name FROM Account WHERE ParentId != null];
    // List<Contact>  conts = [SELECT Id, Name FROM Contact];

    List<SB_Ot_OrgTreeItem.Item> items = SB_Ot_OrgTreeFactory.createOrgTreeItems(acnts[0].Id, Account.getSObjectType());
    SB_Ot_OrgTreeItem.TreeItem root = (SB_Ot_OrgTreeItem.TreeItem)items[0];
    root.print();
    System.assert(root.label.startsWith(rootAcnt.Name));
  }

  @isTest
  static void test_createOrgGridItems_by_Account() {
    Account rootAcnt = [SELECT Id, Name FROM Account WHERE ParentId = null LIMIT 1];
    List<Account> acnts = [SELECT Id, Name FROM Account WHERE ParentId != null];
    // List<Contact>  conts = [SELECT Id, Name FROM Contact];

    List<SB_Ot_OrgTreeItem.Item> items = SB_Ot_OrgTreeFactory.createOrgGridItems(acnts[0].Id, Account.getSObjectType());
    SB_Ot_OrgTreeItem.GridItem root = (SB_Ot_OrgTreeItem.GridItem)items[0];
    root.print();
    System.assert(root.label.startsWith(rootAcnt.Name));
  }

  @isTest
  static void test_createOrgTreeItems_by_Contact() {
    Account rootAcnt = [SELECT Id, Name FROM Account WHERE ParentId = null LIMIT 1];
    List<Contact>  conts = [SELECT Id, Name FROM Contact];

    List<SB_Ot_OrgTreeItem.Item> items = SB_Ot_OrgTreeFactory.createOrgTreeItems(conts[0].Id, Contact.getSObjectType());
    SB_Ot_OrgTreeItem.TreeItem root = (SB_Ot_OrgTreeItem.TreeItem)items[0];
    root.print();
    System.assert(root.label.startsWith(rootAcnt.Name));
  }

  @isTest
  static void test_createOrgGridItems_by_Contact() {
    Account rootAcnt = [SELECT Id, Name FROM Account WHERE ParentId = null LIMIT 1];
    List<Contact>  conts = [SELECT Id, Name FROM Contact];

    List<SB_Ot_OrgTreeItem.Item> items = SB_Ot_OrgTreeFactory.createOrgGridItems(conts[0].Id, Contact.getSObjectType());
    SB_Ot_OrgTreeItem.GridItem root = (SB_Ot_OrgTreeItem.GridItem)items[0];
    root.print();
    System.assert(root.label.startsWith(rootAcnt.Name));
  }

}